[workspace]
resolver = "2"
members = ["crates/cli", "crates/database"]

default-members = ["crates/cli"]

[workspace.dependencies]
rusqlite = "0.32.1"
subprocess = "0.2"
dirs = "5.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
