[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "cli"
path = "src/args.rs"

[[bin]]
name = "smriti"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
database = { path = "../database" }
rusqlite = { workspace = true }
